export const ICONS = {
  arrow_Right: 'arrow_Right',
  bed_icon: 'bed_icon',
  chevron_down: 'chevron_down',
  chevron_up: 'chevron_up',
  curve_down_arrow: 'curve_down_arrow',
  close_icon: 'close_icon',
  close_fill_icon: 'close_fill_icon',
  fb_icon: 'fb_icon',
  hamburger_icon: 'hamburger_icon',
  hide_password: 'hide_password',
  housing_icon: 'housing_icon',
  ig_icon: 'ig_icon',
  location_icon: 'location_icon',
  mail_icon: 'mail_icon',
  minus_icon: 'minus_icon',
  naira_currency: 'naira_currency',
  phone_icon: 'phone_icon',
  plus_icon: 'plus_icon',
  right_arrow: 'right_arrow',
  star_icon: 'star_icon',
  square_icon: 'square_icon',
  toilet_icon: 'toilet_icon',
  twitter_icon: 'twitter_icon',
};
